spring:
  config:
    import: application-secrets.yaml
  application:
    name: TmT

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://phoenixdb.cls4oq20gmca.ap-northeast-2.rds.amazonaws.com:3306/TeemoDB?serverTimezone=Asia/Seoul
    username: admin
    password: admin1013

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:5173/login/kakao/code"
#            redirect-uri: "https://www.teemobudget.site/login/kakao/code"
            authorization-grant-type: authorization_code
            scope: 
            client-name: Kakao
            provider: kakao
          google:
            redirect-uri: "http://localhost:5173/login/google/code"
#            redirect-uri: "https://www.teemobudget.site/login/google/code"
            authorization-grant-type: authorization_code
            client-name: Google
            provider: google
            scope:
              - openid
              - profile
              - email
              
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id           
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub # Google's unique user identifier


mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.ssafy.TmT.dto, com.ssafy.TmT.entity
  configuration: 
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui
